## 곱셈 계층 구현

In [1]:
from typing import Tuple


class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self, x:float,y:float) -> float:
        self.x = x
        self.y = y 
        out = x * y
        
        return out
    
    def backward(self, dout:float) -> Tuple[float,float]:
        # x와 y를 바꾼다
        dx = dout * self.y
        dy = dout * self.x
        
        return dx,dy

In [ ]:
apple = 100
apple_num = 2
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()



## 덧셈 계층

In [3]:
class AddLayer:
    def __init__(self):
        #덧셈 계층은 흘러 보내기만 하면 되서
        #초기화 필요 없음
        pass 
    
    def forward(self,x:float,y:float) -> float:
        out = x+y
        return out
    
    def backward(self,dout:float) -> Tuple[float,float]:
        dx = dout * 1
        dy = dout * 1
        return dx,dy

## 활성화 계층 

### RELU 함수

In [4]:
class Relu:
    def __init__(self):
        self.mask = None 
    
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout 
        
        return dx 

In [6]:
import numpy as np
x = np.array([[1.0,-0.5], [-2.0,3.0]])
print(x)
mask = (x<=0)
print(mask)

[[ 1.  -0.5]
 [-2.   3. ]]
[[False  True]
 [ True False]]


## 시그모이드

In [2]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        out = sigmoid(x)
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1 - self.out) * self.out

SyntaxError: unexpected EOF while parsing (3391426782.py, line 2)

## Affine 계층

In [5]:
import numpy as np

# 순전파 때의 편향 덧셈
X_dot_W = np.array([[0,0,0], [10,10,10]])
B = np.array([1,2,3])

print(X_dot_W)
print(X_dot_W + B)

# 역전파 때의 편향 덧셈
dY = np.array([[1,2,3],[4,5,6]])
print(dY)
dB = np.sum(dY, axis=0)
print(dB)

[[ 0  0  0]
 [10 10 10]]
[[ 1  2  3]
 [11 12 13]]
[[1 2 3]
 [4 5 6]]
[5 7 9]


In [ ]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self, x):
        self.x = x 
        out = np.dot(x, self.W) + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        
        return dx
    
    